### ISSUE TITLE
TypeError: this.metersReadingData is not a function

### ISSUE THREAD

**Issue by chris-araman** [grzegorz914/homebridge-enphase-envoy#41]
Great work on this plug-in, @grzegorz914.

After updating to 5.4.3, I'm seeing this error and my Envoy appears as "unresponsive":
```
[8/23/2021, 1:31:51 PM] [enphaseEnvoy] Device: 192.168.1.14 Envoy, productionCtData error: TypeError: this.metersReadingData is not a function
    at envoyDevice.updateProductionCtData (/home/ubuntu/.nvm/versions/node/v14.17.5/lib/node_modules/homebridge-enphase-envoy/index.js:2936:209)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by grzegorz914** [comment]
Fixed

**Comment by chris-araman** [comment]
Thanks! It's working now.
